import localFont from 'next/font/local';
import './globals.css';
import { VT323 } from 'next/font/google';
import NavBar from '../Components/NavBar';
import { normalizeConfig } from 'next/dist/server/config';

const spaceFont = VT323({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
});

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={spaceFont.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
